Vagrant.configure("2") do |config|
  config.vm.provider :libvirt do |lv|
    lv.uri = "qemu:///system"
    lv.memory = 2048
    lv.cpus = 2
    lv.storage_pool_name = "Home_LAB"
  end
  config.vm.box = "generic/rocky9"
  config.vm.hostname = "rhcsa-lab"
end
